env:
  node: true
  es6: true
  browser: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 9
rules:
  indent: ['error', 4]
  semi: ['error', 'always']
  no-console: ['off']
  object-curly-spacing: ['error', 'always']
  array-bracket-spacing: ['error', 'always']
  computed-property-spacing: ['error', 'always']
  space-before-blocks: ['error', 'always']
  space-before-function-paren: ['error', 'always']
  space-in-parens: ['error', 'never']
  comma-spacing: ['error']
  quote-props: ['error', 'as-needed']
  quotes: ['error', single, { "allowTemplateLiterals": true }]
  key-spacing: ['error', { "beforeColon": false, "afterColon":true }]
  keyword-spacing: ['error']
  space-infix-ops: ['error', { "int32Hint": false }]
  semi-spacing: ['error', {"before": false, "after": true}]
  arrow-parens: ['error', "as-needed"]
  arrow-body-style: ['error', "as-needed"]
  arrow-spacing: ['error']
